### ISSUE TITLE
Error executing watch

### ISSUE THREAD

**Issue by AnnieChris** [HubSpot/hubspot-cms-vscode#272]
**Describe the bug**
Unable to execute watch from the remote file system

```
Error running command hubspot.remoteFs.watch: path should be a `path.relative()`d string, but got "g:\My_Projects\hubspot_work\growth copy\child.css". This is likely caused by the extension that contributes hubspot.remoteFs.watch.
```

**To Reproduce**
Execute watch from the Remote File System

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/e71f7ce6-f069-43bd-884e-6a84f0120290)

** Environment Versions: **
- VSCode Version: [e.g. 1.93.1] 
- HubSpot VSCode Extension version: 1.1.2, 1.2.2
- OS: [Windows 11]

**Additional context**
New to hubspot. First time setting up. Latest 1.3.0 version does not even fetch the files. So tried with earlier versions. Fetch works but upload does not work (although no error). Watch fails with the above error. Able to run fetch, watch command from node cli without any issue.

**Comment by jsines** [comment]
Thanks for reporting! Got a fix in for your issue with the fetch command that should be going out within a few days. I was unable to reproduce your issue with the `watch` command in my Windows 11 virtual machine - do you have any additional info on the setup that's causing this error? What path are you providing as a `dest` when it prompts for one?

**Comment by AnnieChris** [comment]
I updated to the latest 1.3.1 version. Fetch is working again. But still watch doesn't work. I looked at the logs in VS code and this is what's logged
```
2024-09-28 21:54:25.727 [error] RangeError: path should be a `path.relative()`d string, but got "e:\annie\hubspot\sandbox\XXXXXX\CSS_JS\Color_Shifting.js"
	at _ (c:\Users\annie\.vscode\extensions\hubspot.hubl-1.3.1\dist\extension.js:2:238346)
	at v (c:\Users\annie\.vscode\extensions\hubspot.hubl-1.3.1\dist\extension.js:2:238395)
	at y._test (c:\Users\annie\.vscode\extensions\hubspot.hubl-1.3.1\dist\extension.js:2:239769)
	at y.ignores (c:\Users\annie\.vscode\extensions\hubspot.hubl-1.3.1\dist\extension.js:2:240033)
	at u (c:\Users\annie\.vscode\extensions\hubspot.hubl-1.3.1\dist\extension.js:2:77050)
	at c:\Users\annie\.vscode\extensions\hubspot.hubl-1.3.1\dist\extension.js:2:77131
	at Array.filter (<anonymous>)
	at b (c:\Users\annie\.vscode\extensions\hubspot.hubl-1.3.1\dist\extension.js:2:638782)
	at async c:\Users\annie\.vscode\extensions\hubspot.hubl-1.3.1\dist\extension.js:2:638612
	at async h (c:\Users\annie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:161:210546) hubspot.remoteFs.watch {"value":"HubSpot.hubl","_lower":"hubspot.hubl"}

```

**Comment by brandenrodgers** [comment]
Checking in (quite a while later 😅), is this still an issue for you? We've since updated the library that we use under the hood for the "watch" behavior, and it's possible that might have fixed this.
